####################################################################
#                                                                  #
#  Дополнительные настройки проекта для непрерывной интеграции.    #
#  В общем случае должны быть установлены в значения по умолчанию  #
#                                                                  #
####################################################################

variables:

  # 
  WCI_VERSION: "0.9.7"

  # [ON] Включить отчет о покрытии тестами (отображается в запросах на слиение)
  CODE_COVERAGE: "ON"

  # [OFF] Выключить все опции предупреждений для всех веток
  DISABLE_WARNINGS: "OFF"

  # [ON] Включить расширенные опции предупреждений для всех веток
  EXTRA_WARNINGS: "ON"

  # [ON] Включить пароидальный уровень предупреждений для master
  PARANOID_WARNINGS: "ON"

  # [OFF] Сборка в статике или динамике
  BUILD_SHARED_LIBS: "OFF"

  # [ON] Сборка в статике или динамике. Отлючает -static-libgcc -static-libstdc++
  BUILD_SYSTEM_SHARED_LIBS: "OFF"

  # ./b2 --prefix=/usr/monamour/boost link=static threading=multi runtime-link=static install
  # ./b2 --prefix=/usr/monamour/boost link=shared threading=multi runtime-link=shared install
  BOOST_ROOT: "/usr/monamour/boost"

  ROCKSDB_ROOT: "/usr/monamour/rocksdb"

  # [ON] Собирать тесты
  BUILD_TESTING: "ON"

  # [OFF] Позволить собмодулям опережать свою master-ветку
  ALLOW_AHEAD_MASTER: "OFF"

  # После успешного пуша в мастер, запустит "обновление" следующего проекта
  NEXT_PROJECT: ""

